site_name: Sauron Engine
site_description: Sauron engine is an easy to use Automation/ETL/Rule Engine.

theme:
  name: "material"
  palette:
    primary: "red"
    accent: "amber"

repo_name: jlugao/sauron-rule-engine
repo_url: https://github.com/jlugao/sauron-rule-engine
edit_uri: ""

nav:
  - Sauron: "index.md"
  - Tutorial:
      - Getting Started: "getting_started.md"
      - Schema Generation: "schema.md"
      - Runtime Metrics: "runtime_metrics.md"

markdown_extensions:
  - admonition
  - codehilite
  - extra
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
