[tool.poetry]
name = "sauron-rule-engine"
version = "0.1.5"
description = "A simple rule engine implemented in python"
authors = ["jlugao <joaolhullier@gmail.com>"]
readme = "README.md"
repository = "https://github.com/jlugao/sauron-rule-engine"
license = "MIT"


[tool.poetry.dependencies]
python = "^3.6"
pydantic = "^0.29.0"


[tool.poetry.dev-dependencies]
isort = "*"
pytest = "^3.0"
coverage = "4.5.3"
coveralls = "^1.8"
flake8 = "^3.7"
black = {version = "^18.3-alpha.0",allows-prereleases = true}
pre-commit = {version = "^1.17",allows-prereleases = true}
pytest-cov = "^2.7"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

